name: train-model
channels:  
  - conda-forge  
  - defaults
dependencies:  
  - joblib=1.0.1  
  - matplotlib=3.4.2  
  - numpy=1.20.3  
  - pandas=1.3.2  
  - pip=21.0.1  
  - pulp=2.5.0  
  - python=3.8.11  
  - setuptools=52.0.0  
  - statsmodels=0.12.2  
  - wheel=0.37.0  
  - scipy==1.7.3  
  - pip:      
    - azureml-core==1.33.0.post1      
    - pulp==2.5.0